name: Build and Deploy Code Updates to Azure (No Tests, No DB Re-init)

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'        # Any file under the src directory
      - 'pom.xml'       # Changes to your Maven build file
      - '.github/workflows/**' # Also trigger on workflow changes
  pull_request: # Build on PRs to main if code changes, but don't deploy
    branches: [ main ]
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/**'

env:
  AZURE_WEBAPP_NAME: cvk-ecommerce-app
  AZURE_WEBAPP_PACKAGE_PATH: 'target/EcommerceApp.war'
  JAVA_VERSION: '8'
  RESOURCE_GROUP: 'ecommerce-rg'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin' 
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean package -B -DskipTests

    # Deployment steps - only run for pushes to the main branch
    - name: Login to Azure
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: azure/login@v1 
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}