name: Build and Deploy Code Updates to Azure (No Tests, No DB Re-init)

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: cvk-ecommerce-app         # Your existing Web App name
  AZURE_WEBAPP_PACKAGE_PATH: 'target/EcommerceApp.war' # Specific path to your WAR file
  JAVA_VERSION: '8'
  RESOURCE_GROUP: 'ecommerce-rg'             

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin' 
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean package -B -DskipTests # Skip tests

    # Only proceed to deploy if on the main branch
    - name: Deploy to Azure Web App
      if: github.ref == 'refs/heads/main'
      uses: azure/login@v1 
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: | # This run step is part of the Deploy step if AZURE_CREDENTIALS is used
        # Deploy using Azure Web Apps Deploy action
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          # publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Option 1: Use publish profile
          # If not using publish-profile, ensure AZURE_CREDENTIALS service principal has deployment rights